event_inherited();
top_left_bound_x = 0;
top_left_bound_y = 0;
bot_right_bound_x = room_width - sprite_width;
bot_right_bound_y = room_height - sprite_height;
pre_move_x = 0;
pre_move_y = 0;
moved_x = 0;
moved_y = 0;
moved_dist = 0;
weight = 1;
can_be_pushed = true;
bidirectional_magnitude_factor = 1/sqrt(2);